### ISSUE TITLE
Fix charset or encoding support for PostgreSQL

### ISSUE THREAD

**Issue by ocram** [delight-im/PHP-DB#10]
Until now, we have been [setting](https://github.com/delight-im/PHP-DB/blob/10621b7bfb45b543ead739dd76dbc95704ec1288/src/PdoDataSource.php#L240) the charset or encoding for the DSN of PostgreSQL databases in the `PdoDataSource` class like this:

```
…;charset=…
```

But [apparently](https://github.com/delight-im/PHP-Auth/issues/116), this does not work. More specifically, it seems to be invalid syntax and may cause the connection to fail.

Alternatively, we may use the following syntax, which seems to work without problems:

```
…options='--client_encoding=…'…
```

That would mean we have to change the [line in question](https://github.com/delight-im/PHP-DB/blob/10621b7bfb45b543ead739dd76dbc95704ec1288/src/PdoDataSource.php#L240) from

```php
$components[] = 'charset='.$this->charset;
```

to

```php
$components[] = 'options=\'--client_encoding=' . $this->charset . '\'';
```

It would be great if someone could test this by going into `vendor/delight-im/db/src/PdoDataSource.php` in their project’s directory and changing the line.

We are pretty sure we had tested this once, but perhaps warnings or errors were suppressed. It is important that we determine if this is a breaking change, if the syntax changed in some version of PostgreSQL and whether we could break any application using this library.

**Comment by MB34** [comment]
This code seems to work:

    $components[] = 'options=\'--client_encoding='.$this->charset.'\'';

You forgot the closing '

**Comment by ocram** [comment]
That’s great, thanks!

Our pieces of code seem to be identical, and I don’t think I forgot the quote.

Now we only need to know if this way of specifying the charset has enough backward compatibility, i.e. whether it has been supported for a longer time already. Maybe also whether the other way (still used in this library) has ever been supported. After that, we’ll be able to merge this change.

For now, you can just apply this modification in your local copy in the `vendor` directory, of course.

**Comment by ocram** [comment]
It seems that support for the `client_encoding` option has been present since *at least* PostgreSQL 9.1, which means that we can safely merge this fix if we don’t want to support older versions. I think 9.1 is fine as a base.

Further, since version 9.1 exactly, we should be able to use `client_encoding` as an attribute directly, i.e. without having to wrap it in an option.

So could you please test one last change? Please try replacing

```php
$components[] = 'options=\'--client_encoding=' . $this->charset . '\'';
```

with

```php
$components[] = 'client_encoding=\'' . $this->charset . '\'';
```

or simply

```php
$components[] = 'client_encoding=' . $this->charset;
```

Thank you!

**Comment by MB34** [comment]
Yes, it worked. Got through that and settled on the issue with the double quotes around the table name.

**Comment by ocram** [comment]
Thanks!

Fixed in https://github.com/delight-im/PHP-DB/commit/8fcf5ecb26288757fcc820b854ad1209c7b3f5d7.
