### ISSUE TITLE
How does function getLastInsertId work?

### ISSUE THREAD

**Issue by vulantro** [delight-im/PHP-DB#17]
Does it return the last row's id which my application inserted, or the last row's id anyone inserted who has access to the database? If no sequence name, does it refer to all of sequences and chooses the last used?

**Comment by ocram** [comment]
Excellent questions, thank you!

In general, all this depends on the underlying driver for your specific database software.

But for MySQL/MariaDB and PostgreSQL, at least, the IDs should be maintained and returned on a per-connection basis, i.e. you will see the IDs of the records you inserted yourself, in your own application, in the same script, for the same request.

With MySQL/MariaDB, you don’t need to specify any sequence names, as it works with `AUTO_INCREMENT` values. With PostgreSQL, you should always specify a sequence name, so omitting the value and relying on a default sequence or recently used sequence should not be something you need to think about.

Internally, for MySQL/MariaDB, this should be using `LAST_INSERT_ID()`, and for PostgreSQL, it should be using `CURRVAL(mySequence)` or `CURRVAL(PG_GET_SERIAL_SEQUENCE(myTable, myColumn))`. In any way, it just uses [`PDO::lastInsertId`](https://www.php.net/manual/en/pdo.lastinsertid.php) internally.

Hope that helps!
