### ISSUE TITLE
Input escaping

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-DB#19]
Hello great library, I was just wondering if you'd be able to provide me an example of how to insert using place holders;
https://github.com/delight-im/PHP-DB#input-escaping

Normally I'd just use prepare since I cannot see prepare I am not sure how to execute it with the way you have in the library:

How would I execute this with placeholders:

```
$db->insert(
    'books',
    [
        // set
        'name' => 'Don Quixote',
        'author' => 'Miguel de Cervantes',
        'year' => 1612
    ]
);
```
Cheers

**Comment by ocram** [comment]
Thanks!

The example you cited, i.e.

```php
$db->insert(
    'books',
    [
        'name' => 'Don Quixote',
        'author' => 'Miguel de Cervantes',
        'year' => 1612
    ]
);
```

should be equivalent to the placeholder version

```php
$db->exec(
    "INSERT INTO books (name, author, year) VALUES (?, ?, ?)",
    [
        'Don Quixote',
        'Miguel de Cervantes',
        1612
    ]
);
```

or the literal version

```php
$db->exec("INSERT INTO books (name, author, year) VALUES ('Don Quixote', 'Miguel de Cervantes', 1612)");
```

Does that help?
