### ISSUE TITLE
Perform operations with the fields

### ISSUE THREAD

**Issue by brahimbjz** [delight-im/PHP-DB#20]
How could an update be made of a field, whose new value is the current one + 1?
In a normal sentence it would be like this, but I don't know how to apply it to your library:

`UPDATE table SET views = views + 1 WHERE id = ?`

**Comment by brahimbjz** [comment]
```
$db->increment(
    'users',
    [ 'balance' => 25 ],
    [ 'username' => 'Adam' ]
);
```
I found it. Sorry

**Comment by ocram** [comment]
No, good question, you were right, and that `Database#increment` method has not actually been implemented yet.

However, the thread where you probably found that method has the alternative solution as well: https://github.com/delight-im/PHP-DB/pull/13 That basic `Database#exec` solution works already today, and is exactly what you originally wanted, i.e. using your suggested first SQL statement with this library.
