### ISSUE TITLE
Delete multi element with array of ids

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-DB#21]
Is there a method for delete a group of element passing an array of ids maybe count the element of the array or some way ?

-- ADDED: I could to use exec with clause WHERE id IN () 

IF NOT, with a foreach how I can use the transaction for rollback ?

```
$db->beginTransaction();
try{
foreach($a AS $b){
$db->delete(
    'books', [ 'id' => $b]
);
// Operation 2 here
}
$db->commit();
} catch (Exception $e) {
$db->rollBack();
}
```

Thanks.

**Comment by ocram** [comment]
Thanks! This is perhaps the most important feature that’s still missing. It takes a little work to do this safely. It’s already tracked here: https://github.com/delight-im/PHP-DB/issues/7 Using a loop for this is not as efficient.
