### ISSUE TITLE
transactions example

### ISSUE THREAD

**Issue by AdamSEY** [delight-im/PHP-DB#3]
Hi, I know that transactions should begin after prepare statements and before executing the SQL query, but with your library, we should begin the transaction before the select query is that right?

Can you just give a simple example since it's not clear in readme file?

**Comment by AdamSEY** [comment]
Does beginning a transaction locking the table?

**Comment by ocram** [comment]
Not sure about the rule that you cited. It’s actually much simpler than you think, I guess:

```php
$db->beginTransaction();

try {
   // Operation 1 of 3
    $row = $db->selectRow(
        'SELECT author, year FROM books WHERE author <> ? ORDER BY year ASC LIMIT 0, 1',
        [ 'Miguel de Cervantes' ]
    );

   // Operation 2 of 3
    $db->delete(
        'books',
        [
            // where
            'author' => 'C. S. Lewis',
            'year' => 1949
        ]
    );

   // Operation 3 of 3
    $db->insert(
        'books',
        [
            // set
            'name' => 'Don Quixote',
            'author' => 'Miguel de Cervantes',
            'year' => 1612
        ]
    );

    $db->commit();
}
catch (Exception $e) {
    $db->rollBack();
}
```

Just to give a simple example (that doesn’t really make sense in practice, though). Of course, you’ll also want to do some other things, e.g. logging the exception or displaying a message to the user.

Essentially, it works like this:

 1. You start the transaction.
 1. In the `try` block, you execute your desired operations and finally commit the transaction.
 1. In the `catch` block, you roll back the transaction.

Hope that helps!
