### ISSUE TITLE
Unable to execute LIKE statements

### ISSUE THREAD

**Issue by creativenoobie** [delight-im/PHP-DB#6]
Hey,

I'm trying to execute following statement:

`$exists = $this->db->exec("SHOW COLUMNS FROM table_name LIKE ?", [$column_name] );`

It throws a syntax error violation.
While running this statement directly on mysql server, it works with:
`SHOW COLUMNS FROM table_name LIKE 'column_name'`

I tried executing statement like:
`$exists = $this->db->exec("SHOW COLUMNS FROM table_name LIKE '?'", [$column_name] );`
(Inserting single quotes around ?), It returns an invalid result, which was not correct, of course.
After a quite, debugging and logs, I found that my statement is executed as:
`SHOW COLUMNS FROM table_name LIKE '?'`

Is there any execute the statement? It would be of great help!

Thanks in advance!

**Comment by ocram** [comment]
To be honest, I don’t really know that syntax

```sql
SHOW COLUMNS FROM table_name LIKE ?
```

which you have been using. Perhaps `PDO` (which this library uses) cannot compile this to a prepared statement. I don’t know.

Try using

```sql
SHOW COLUMNS FROM table_name WHERE Field = ?
-- or
SHOW COLUMNS FROM table_name WHERE Field LIKE ?
```

instead and it should work.

Hope that helps!

**Comment by creativenoobie** [comment]
Thanks! This works

**Comment by ocram** [comment]
Great to hear that, thanks!
